```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(easypackages)
my_packages <- c("tidyverse", "googlesheets", "xtable", "extrafont")
libraries(my_packages)


dna <- gs_title("dna") %>%
  gs_read(ws = "Mayo")



colnames(dna)


```


# AVAILABLE BUILDINGS IN TIJUANA MARKETS AT Q1 2018


```{r echo=FALSE, results='asis'}

print.xtable(xtable(dna %>%
  select(`Empresa de Arrendamiento`, Nombre, Submercado, costo_de_arrendamiento) %>%
  spread(Submercado, costo_de_arrendamiento) %>%
  group_by(`Empresa de Arrendamiento`, Nombre) %>%
  summarise("Mean El Florido"= mean(`El Florido - Boulevard 2000`, na.rm = TRUE))   %>%
  filter(!is.na(`Mean El Florido`)) %>%
  arrange(desc(`Mean El Florido`)), caption = "Mean lease rate El Florido - Boulevard 2000"), comment = FALSE, caption.placement = "top", include.rownames = FALSE)



```




```{r echo=FALSE, results='asis'}

print.xtable(xtable(dna %>%
  select(`Empresa de Arrendamiento`, Nombre, Submercado, costo_de_arrendamiento) %>%
  spread(Submercado, costo_de_arrendamiento) %>%
  group_by(`Empresa de Arrendamiento`, Nombre) %>%
  summarise("Mean Pacifico"= mean(`Pacifico - Nordika`, na.rm = TRUE))   %>%
  filter(!is.na(`Mean Pacifico`)) %>%
  arrange(desc(`Mean Pacifico`)), caption = "Mean lease rate Pacifico - Nordika"), comment = FALSE, caption.placement = "top", include.rownames = FALSE)



```



```{r echo=FALSE, results='asis'}

print.xtable(xtable(dna %>%
  select(`Empresa de Arrendamiento`, Nombre, Submercado, costo_de_arrendamiento) %>%
  spread(Submercado, costo_de_arrendamiento) %>%
  group_by(`Empresa de Arrendamiento`, Nombre) %>%
  summarise("Mean Otay"= mean(`Otay - Alamar`, na.rm = TRUE))   %>%
  filter(!is.na(`Mean Otay`)) %>%
  arrange(desc(`Mean Otay`)), caption = "Mean lease rate Otay - Alamar"), comment = FALSE, caption.placement = "top", include.rownames = FALSE)
```




```{r echo=FALSE, results='asis'}

print.xtable(xtable(dna %>%
  select(`Empresa de Arrendamiento`, Nombre, Submercado, costo_de_arrendamiento) %>%
  spread(Submercado, costo_de_arrendamiento) %>%
  group_by(`Empresa de Arrendamiento`, Nombre) %>%
  summarise("Mean Insurgentes"= mean(`Insurgentes - El Aguila`, na.rm = TRUE))   %>%
  filter(!is.na(`Mean Insurgentes`)) %>%
  arrange(desc(`Mean Insurgentes`)), caption = "Mean lease rate Insurgentes - El Aguila"), comment = FALSE, caption.placement = "top", include.rownames = FALSE)

```




```{r echo=FALSE, results='asis'}

print.xtable(xtable(dna %>%
  select(`Empresa de Arrendamiento`, Nombre, Submercado, costo_de_arrendamiento) %>%
  spread(Submercado, costo_de_arrendamiento) %>%
  group_by(`Empresa de Arrendamiento`, Nombre) %>%
  summarise("Mean La mesa"= mean(`La mesa - Via Rapida`, na.rm = TRUE))   %>%
  filter(!is.na(`Mean La mesa`)) %>%
  arrange(desc(`Mean La mesa`)), caption = "Mean lease rate La mesa - Via Rapida"), comment = FALSE, caption.placement = "top", include.rownames = FALSE)

```



```{r}

library(ggrepel)


dna %>%
  select(`Empresa de Arrendamiento`, Nombre, Submercado, costo_de_arrendamiento) %>%
  group_by(`Empresa de Arrendamiento`, Submercado) %>% 
  summarise(lease = mean(costo_de_arrendamiento, na.rm = TRUE)) %>%
  ggplot(aes(x = reorder(`Empresa de Arrendamiento`,lease), lease)) + 
  geom_point(aes(colour = Submercado)) + 
  coord_flip() + 
  theme_minimal() +
  xlab(label = NULL) +
  ylab(label = "Leasing rate") +
  theme(legend.title = element_text(size = 9), legend.text = element_text(size = 6), legend.position = "bottom")



```

```{r}

dna %>%
  select(`Empresa de Arrendamiento`, Nombre, Submercado, costo_de_arrendamiento) %>%
  group_by(Submercado) %>% 
  summarise(lease = mean(costo_de_arrendamiento, na.rm = TRUE),
         n = n()) %>%
  ggplot(aes(x = reorder(Submercado,lease), lease, colour = Submercado)) + 
  geom_point(aes(size = n)) + 
  geom_text_repel(aes(label = factor(n))) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") + 
  ggtitle("Available buildings by submarket and average lease rate")



```





```{r}
dna %>%
  select(`Empresa de Arrendamiento`, Nombre, Submercado, costo_de_arrendamiento, Desarrollardor) %>%
  group_by(Submercado, Nombre, `Empresa de Arrendamiento`, Desarrollardor) %>% 
  summarise(lease = mean(costo_de_arrendamiento, na.rm = TRUE)) %>%
  ggplot(aes(x = reorder(Submercado, lease), y = lease)) + 
  geom_boxplot() +
  geom_point() + 
  coord_flip() + 
  theme_minimal() + 
  ggtitle("Average asking price dispersion by submarket")


```






