---
title: "Informe trimestral del mercado de bienes raíces para uso industrial, comercial y habitacional en México y Tijuana"
subtitle: <h1>Primer trimestre de 2018 Enero-Marzo<h1>
author: "José Eduardo Jaramillo Barrera"
date: "16 de abril de 2018"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(easypackages)
my_packages <- c("readr", "readxl", "tidyverse", "lubridate", "xts",  "tidyquant", "ggrepel", "reshape2", "ggseas")
libraries(my_packages)

db <- read.csv("BIE_BIE20180413143330.csv", encoding = "Latin-1")

db <- read_excel("BIE_BIE20180416182227.xls", 
                                    skip = 1)

```





# Comportamiento de la economía en general oferta
## Producto interno bruto trimestral en el sector manufacturero


```{r}

db %>%
  select(contains("Indicador global de la actividad económica Tendencia"), Periodo) %>%
  rename_all(
    funs(
      stringr::str_replace_all(.,"(.+>)", "")
    )
  ) %>%
  rename("IGAE" = " Indicador global de la actividad económica Tendencia f3/ (Índice base 2013=100)") %>%
  separate(Periodo, into = c("year", "month"), sep = "/") %>%
  filter(!is.na(IGAE)) %>% 
  mutate(dia = 01,
         fecha = mdy(paste0(month, "-", dia, "-", year)),
         rocigae = ROC(IGAE)) %>%
  ggplot(aes(fecha, rocigae)) + 
  geom_line() +
  labs(title = "Indicador Global de la Actividad Económica",
       subtitle = "Tendencia de largo plazo IGAE",
       caption = "Fuente: Elaboración propia con datos de INEGI") +
  scale_x_date(date_breaks = "3 year", date_labels = "%y %b") +
  theme_tq()

```






## Indicador Global de la actividad económica

En la siguiente gráfica se observa el Indicador Global de la Actividad Económica para México

```{r}
db %>%
  select(contains("Indicador.global.de.la.actividad.económica"), Periodo) %>%
  rename("IGAE" = "Indicadores.económicos.de.coyuntura...Indicador.global.de.la.actividad.económica..base.2013...Series.originales...Índice.de.volumen.físico.Total.p2...f3...Índice.base.2013.100..Mensual") %>%
  select(Periodo, IGAE) %>%
  filter(!is.na(IGAE)) %>%
  mutate(Periodo = ymd(as_date(paste0(Periodo, sep = "/" ,"01")))) %>%
  filter(Periodo > "2015-01-01") %>%
  ggplot(aes(x = Periodo, y = IGAE, label = paste0(month(Periodo, label = TRUE), "-" ,year(Periodo)))) +
  geom_point() +
  geom_vline(aes(xintercept = as.numeric(Periodo[c(24)])), linetype = 4, colour = "black") +
  geom_line() +
  geom_ma(n = 3) + 
  ggtitle("Indicador global de la actividad económica") +
  theme_tq()
```



## Incremento porcentual respecto al periodo pasado IGAE

```{r}

db %>%
  select(contains("Indicador.global.de.la.actividad.económica"), Periodo) %>%
  rename("IGAE" = "Indicadores.económicos.de.coyuntura...Indicador.global.de.la.actividad.económica..base.2013...Series.originales...Índice.de.volumen.físico.Total.p2...f3...Índice.base.2013.100..Mensual") %>%
  select(Periodo, IGAE) %>%
  filter(!is.na(IGAE)) %>%
  mutate(Periodo = ymd(as_date(paste0(Periodo, sep = "/" ,"01"))),
         prc_igae = c(NA, exp(diff(log(IGAE)))-1),
         color = if_else(prc_igae < 0, "negative", "positive")) %>%
  filter(Periodo > "2015-01-01") %>%
  ggplot(aes(x = Periodo, y = prc_igae*100)) +
  geom_bar(stat = "identity", position = "dodge", aes(fill = color)) +
  geom_text_repel(aes(label = round(prc_igae * 100, digits = 2)), size = 3) +
  theme_tq() + 
  scale_fill_manual(values = c(positive = "#6ebe4c" , negative = "#ca2128" )) + 
  scale_x_date(date_breaks = "3 month", date_labels = "%b") +
  ylab(label = "Incremento porcentual") +
  theme(legend.position = "none") + 
  geom_vline(aes(xintercept = as.numeric(Periodo[c(24)])), linetype = 4, colour = "black") +
  labs(title = "Indicador global de la actividad económica",
       subtitle = "Incremento porcentual respecto al mes pasado",
       caption = "Fuente: Elaboración propia con datos de INEGI")
  
```








## Número de empresas registradas en IMMEX


```{r warning=FALSE}
db %>%
  select(contains("Número.de.establecimientos.activos.según.entidades.federativas.y.municipios.Total.nacional"), Periodo) %>%
  rename("immex_no" = "Manufacturas...Industria.manufacturera..maquiladora.y.de.servicios.de.exportación..IMMEX....Por.entidad.federativa...Establecimientos.manufactureros...Número.de.establecimientos.activos.según.entidades.federativas.y.municipios.Total.nacional.b...p9...f6...Número.de.establecimientos..Mensual") %>%
  filter(!is.na(immex_no)) %>%
  separate(Periodo,into = c("anio", "mes")) %>%
  mutate(day = 01,
    periodo = ymd(as_date(paste(anio, mes, day, sep = "/")))) %>%
  group_by(year(periodo)) %>%
  summarise(m_immex = mean(immex_no, na.rm = TRUE)) %>%
  ggplot() + 
  geom_line(aes(x = `year(periodo)`, y = m_immex)) +
  geom_point(aes(x = `year(periodo)`, y = m_immex)) +
  geom_label_repel(aes(x = `year(periodo)`, y = m_immex, label = round(m_immex))) + 
  theme_minimal() + 
  ggtitle("Empresas registradas en IMMEX") +
  xlab("Año") +
  ylab("Número de empresas registradas") + 
  scale_x_continuous(breaks = c(2007,2008,2009,2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018))
  
  

```

```{r}

```

